name:       Bsale Templates Docs
url:        https://bsale-io.github.io/
baseurl:    /template-docs
markdown:   Kramdown


# sass
sass:
  style:    compressed


collections:
  tester:
    output: true

future: true

# plugin
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag