name:       Bsale Templates Docs
url:        https://bsale-io.github.io/template-docs
baseurl:    /
markdown:   Kramdown

# link 
permalink:  pretty
relative_permalinks: true

# sass
sass:
  sass_dir: _sass
  style:    :compressed

# plugin
plugins:
  - jemoji
  - jekyll-sitemap

# Collection
#collections:
# liquid:
#    output:     true
#    permalink:  /liquid/:path/
    
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"