name:       Bsale Templates Docs
url:        https://bsale-io.github.io
baseurl:    /template-docs
markdown:   Kramdown
permalink:  pretty
collections:
  test:
    output: true

# sass
sass:
  sass_dir: _sass
  style:    :compressed

# plugin
plugins:
  - jemoji
  - jekyll-sitemap

# Collection
collections:
  liquid:
    output:     true
    permalink:  /liquid/:path/
    
defaults:
  - scope:
      path: ""
      type: "liquid"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"