name:       Bsale Templates Docs
url:        https://bsale-io.github.io
baseurl:    /template-docs
markdown:   Kramdown
collections:
  test:
    output: true

# sass
sass:
  sass_dir: _sass
  style:    :compressed

# plugin
plugins:
  - jemoji
  - jekyll-sitemap