name: test
markdown: Kramdown
url: https://bsale-io.github.io/template-docs/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - 
    scope:
      path: "assets/img"
    values:
      image: true
plugins:
- jekyll-menus