name:       Bsale Templates Docs
url:        https://bsale-io.github.io/
baseurl:    /template-docs
markdown:   Kramdown

kramdown:
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# sass
sass:
  style:    compressed


collections:
  componentes:
    output: true
  eventos:
    output: true
  liquid:
    output: true
  javascript:
    output: true
  seo:
    output: true

future: true

# plugin
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

  relative_links:
    enabled:     true
    collections: true